### ISSUE TITLE
When will new features come?

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#128]
I wonder when you will customize the Hello friend add part. Can you post a roadmap.
They earn points by sending a heart to each other between friends.
And they can spend those points in a small store.
And most importantly, friends send private messages.
Please make these updates in the next update.
And add a simple leaderboard.

**Comment by insthync** [comment]
Just uploaded yesterday https://suriyun-production.github.io/turnbase-rpg-docs/#/pages/000-changelog

**Comment by dclgamingtr** [comment]
Asset store also does not show updates yet.

**Comment by insthync** [comment]
Because it have to wait asset store team to publish it.

**Comment by dclgamingtr** [comment]
Clan boss has not been added. You said it would be in the update.

**Comment by insthync** [comment]
Yes, I know, it is under-development, you can see code changes in an open-source repo such as https://github.com/insthync/rpg-php-service. I have to upload that latest update because it has someone rushing me to release a new update like you do here.
And there are also more new feature requests every time when I just release a new update package, now it's like I swimming in the ocean, I don't know when this will be done.
Don't disturb me like this it has no benefit.

**Comment by dclgamingtr** [comment]
I am not saying anything extra, you said there will be a clan boss in the update.

**Comment by insthync** [comment]
The point of whats I told you is I know I said that. You don't have to repeat it, I am going to finish it, but I have to upload that update.
