### ISSUE TITLE
v1.16d Hide the equipped items and In Team characters

### ISSUE THREAD

**Issue by xcygame** [suriyun-production/turnbase-rpg-docs#146]
Hi Suriyun,
I tested the new features for the first time. So I checked "not show items and characters".
![00](https://user-images.githubusercontent.com/41316408/111623532-7602e200-8825-11eb-839e-16b0c9ec2e24.jpg)

But they still exist in the inventory (when equip items or characters in team, there is no reduction of a grid)

For example, when I have 3 items and 2 items equipped, there shuould be 1 item lin the inventory , Instead of the current 3 objects in the inventory.
![0](https://user-images.githubusercontent.com/41316408/111623408-510e6f00-8825-11eb-94f2-1de9e1f22186.jpg)
![1](https://user-images.githubusercontent.com/41316408/111623445-5cfa3100-8825-11eb-9d7c-566be1dbf44f.jpg)

Am I miss something? Or does the current version not support this feature?

Thanks.

**Comment by insthync** [comment]
There is no new settings for UI yet, those settings I made for just don't show "In Team" or "Equipped" message above icons.

**Comment by xcygame** [comment]
> There is no new settings for UI yet, those settings I made for just don't show "In Team" or "Equipped" message above icons.

I see. is there a way to subtract or hidden them from the inventory ? when items is equip and characters is in team.

**Comment by insthync** [comment]
In `UIInventoryManager.cs` you can changes filter codes in `Show` function line `25`

**Comment by xcygame** [comment]
> In `UIInventoryManager.cs` you can changes filter codes in `Show` function line `25`

I found the code, but I'm not sure how to modify it. Could you take a screenshot?

**Comment by HajiyevEl** [comment]
> 
> 
> > In `UIInventoryManager.cs` you can changes filter codes in `Show` function line `25`
> 
> I found the code, but I'm not sure how to modify it. Could you take a screenshot?

In UIInventoryManager.cs find this line: 
`var list = PlayerItem.DataMap.Values.Where(a => UIItemListFilter.Filter(a, filterSetting)).ToList();`
change to this:
`var list = PlayerItem.DataMap.Values.Where(a => UIItemListFilter.Filter(a, filterSetting) && a.EquippedByItem != null).ToList();`

**Comment by xcygame** [comment]
> > > In `UIInventoryManager.cs` you can changes filter codes in `Show` function line `25`
> > 
> > 
> > I found the code, but I'm not sure how to modify it. Could you take a screenshot?
> 
> In UIInventoryManager.cs find this line:
> `var list = PlayerItem.DataMap.Values.Where(a => UIItemListFilter.Filter(a, filterSetting)).ToList();`
> change to this:
> `var list = PlayerItem.DataMap.Values.Where(a => UIItemListFilter.Filter(a, filterSetting) && a.EquippedByItem != null).ToList();`

Thank you for your reply, but it doesn't seem to work. Here are some screenshots after modified code:

Inventory become unusable
![0](https://user-images.githubusercontent.com/41316408/111727586-20224e80-88a6-11eb-831c-9c4f68b99bbb.jpg)
In team character is still in the inventory
![1](https://user-images.githubusercontent.com/41316408/111727597-231d3f00-88a6-11eb-8c0e-1773d3d20b50.jpg)

**Comment by HajiyevEl** [comment]
> In team character is still in the inventory

Oh my, sorry, it was evening and i didn't look properly at script hierarchy. Actually it should be `UIEquipmentManager` and not `UIInventoryManager`.

I changed my project and script too much so i can't tell which line it is, just find it yourself. Find this line in **`UIEquipmentManager`**:

`var list = PlayerItem.DataMap.Values.Where(a => a.PlayerId == playerId && a.EquipmentData != null).ToList();`

**change to:**

`            var list = PlayerItem.DataMap.Values.Where(a => a.PlayerId == playerId && a.EquipmentData != null && a.EquippedByItem == null).ToList();`

This will **hide** already equipped items in character equipment window **ONLY**. (The one you did screenshot in first comment)

If you want to hide all equipped items from global inventory :

In **`UIInventoryManager.cs`** find this line:
`var list = PlayerItem.DataMap.Values.Where(a => UIItemListFilter.Filter(a, filterSetting)).ToList();`

**change to this:**

`var list = PlayerItem.DataMap.Values.Where(a => UIItemListFilter.Filter(a, filterSetting) && a.EquippedByItem == null).ToList();`

(Yesterday i had mistake here - `a.EquippedByItem != null`. It should have been `a.EquippedByItem == null`)

By the way, when checkmarking `Not Show In Team Status`, it just disables 'In Team' **text** component. 
If you want to remove Characters that are already in Formation (Team) from inventory grid, once again change that line in `UIInventoryManager` to this:

`var list = PlayerItem.DataMap.Values.Where(a => UIItemListFilter.Filter(a, filterSetting) && a.EquippedByItem == null && !(a.InTeamFormations.Count > 0)).ToList();`

But even this is not all. Because inventory in Arena Formations uses `UIItemList` and not `UIInventoryManager`, so, if you want to filter heroes in Arena Formation inventory too, go to **`UIFormationManager`**, find this line:

 `var list = PlayerItem.DataMap.Values.Where(a => a.PlayerId == playerId && a.CharacterData != null).ToList();`

**change to:**

`var list = PlayerItem.DataMap.Values.Where(a => a.PlayerId == playerId && a.CharacterData != null && !(a.InTeamFormations.Count > 0)).ToList();`

I think that's all. What a pain in the a## isn't it ?

**Comment by xcygame** [comment]
> > In team character is still in the inventory
> 
> Oh my, sorry, it was evening and i didn't look properly at script hierarchy. Actually it should be `UIEquipmentManager` and not `UIInventoryManager`.
> 
> I changed my project and script too much so i can't tell which line it is, just find it yourself. Find this line in **`UIEquipmentManager`**:
> 
> `var list = PlayerItem.DataMap.Values.Where(a => a.PlayerId == playerId && a.EquipmentData != null).ToList();`
> 
> **change to:**
> 
> ` var list = PlayerItem.DataMap.Values.Where(a => a.PlayerId == playerId && a.EquipmentData != null && a.EquippedByItem == null).ToList();`
> 
> This will **hide** already equipped items in character equipment window **ONLY**. (The one you did screenshot in first comment)
> 
> If you want to hide all equipped items from global inventory :
> 
> In **`UIInventoryManager.cs`** find this line:
> `var list = PlayerItem.DataMap.Values.Where(a => UIItemListFilter.Filter(a, filterSetting)).ToList();`
> 
> **change to this:**
> 
> `var list = PlayerItem.DataMap.Values.Where(a => UIItemListFilter.Filter(a, filterSetting) && a.EquippedByItem == null).ToList();`
> 
> (Yesterday i had mistake here - `a.EquippedByItem != null`. It should have been `a.EquippedByItem == null`)
> 
> By the way, when checkmarking `Not Show In Team Status`, it just disables 'In Team' **text** component.
> If you want to remove Characters that are already in Formation (Team) from inventory grid, once again change that line in `UIInventoryManager` to this:
> 
> `var list = PlayerItem.DataMap.Values.Where(a => UIItemListFilter.Filter(a, filterSetting) && a.EquippedByItem == null && !(a.InTeamFormations.Count > 0)).ToList();`
> 
> But even this is not all. Because inventory in Arena Formations uses `UIItemList` and not `UIInventoryManager`, so, if you want to filter heroes in Arena Formation inventory too, go to **`UIFormationManager`**, find this line:
> 
> `var list = PlayerItem.DataMap.Values.Where(a => a.PlayerId == playerId && a.CharacterData != null).ToList();`
> 
> **change to:**
> 
> `var list = PlayerItem.DataMap.Values.Where(a => a.PlayerId == playerId && a.CharacterData != null && !(a.InTeamFormations.Count > 0)).ToList();`
> 
> I think that's all. What a pain in the a## isn't it ?

Hello, I really appreciate your detailed explanation. The equipment works.

But there are still some problems with the character in the team (it didn't refresh immediately)

1. When the character is in the team, the UI doesn't refresh immediately (but it actually works)
![0](https://user-images.githubusercontent.com/41316408/111784621-9484de00-88f6-11eb-945b-a398c1a9d2d1.jpg)


2. I close and reopen the UI interface, which actually works
![1](https://user-images.githubusercontent.com/41316408/111784637-98b0fb80-88f6-11eb-821a-0253e37c2601.jpg)


3. When the character is not in the team, the UI interface does not refresh immediately too. In fact, it also works. Just close and reopen the UI interface.
![2](https://user-images.githubusercontent.com/41316408/111784478-6901f380-88f6-11eb-872c-aecf96653151.jpg)

Maybe a little bit of setup is missing?

**Comment by HajiyevEl** [comment]
> Maybe a little bit of setup is missing?

I would want to help, but i don't know myself what could be the problem. Let's ask @insthync together.

By the way, @insthync , how to find which character equipped which item?

**Comment by xcygame** [comment]
> > Maybe a little bit of setup is missing?
> 
> I would want to help, but i don't know myself what could be the problem. Let's ask @insthync together.
> 
> By the way, @insthync , how to find which character equipped which item?

Anyway, I appreciate your help. On this question, it is a breakthrough (handshake)  ：）
