### ISSUE TITLE
Tournament type game mode?

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#168]
Hello, can you make a tournament type game mode? A game mode with different gameplay would be great. There is no variety in the game, all modes are similar to each other. Could you please, it will be very good for an online game.

For example, there would be a join button. Those who want to participate click this button and join. It equalizes everyone according to the number of participants and it becomes a tournament. 

Or to give an example, it automatically selects the 10 strongest people. And these people fight in the background automatically in turn. It's not a real-time battle. It will be the same system as in the arena. Only the winner will advance to the next round. Ranking rewards are given at the end of the game. I think it will be a good mod.

Best regards.

**Comment by insthync** [comment]
Ask for a free update? :)

**Comment by dclgamingtr** [comment]
If you create a campaign, we will support you. Just start a campaign.

**Comment by insthync** [comment]
You should give me more information, but I actually want to tell you that I might not have time to finish it as fast as possible.

**Comment by FleksisLV** [comment]
![image](https://user-images.githubusercontent.com/45308506/126897446-7b40534d-25aa-4a65-a664-ff9eacff1cd2.png)
i'am intrested it this too, he talks about this.  Basicaly there is 16 players from beggining, winner fight with winner, and on the end only the two winners fight for the reward.

**Comment by shubhank008** [comment]
I think tournament mode is not too difficult depending on what all is needed. 
Just need to create a fake tourna UI, use arena mode and instead of allowing user to select opponent, we use our code to select the opponent based on bracket.  
All of this info can be managed using a database or even better something like firestore

But for a tournament I think multiplayer is needed first otherwise it will be same as arena, fake oponent controlled by bot.  

I am tinkering around using firebase for the turn-based MP approach instead of using photon or server (which I think Suriyun will do) so if anyone can create a full-fledged working of the tournament mode with details, I can give it a try (but will need time as I am making my game as well).

**Comment by Ragingsura** [comment]
> You should give me more information, but I actually want to tell you that I might not have time to finish it as fast as possible.

a combat over haul would be better to implement with the multiplayer 

players team starts with 0/100 energy standard attack gives energy and player have 20 second to execute a command before the round ends and the enemy take their turn 

with new skills that can recover energy  stop enemy from recovering energy and stealing energy from the enemy.
