### ISSUE TITLE
Forgot Password system.

### ISSUE THREAD

**Issue by dclgamingtr** [suriyun-production/turnbase-rpg-docs#46]
Hello,

There is no change field for the forgotten password in the game. This poses a major problem.
I forgot my password. nothing  made it because your panel is salting.
Please do something to change the password in the input field.
My game is about to end, but I can't publish it.

Best regards.

**Comment by insthync** [comment]
I don't want to do it because it is mostly backend-side work, you should hire other developers to do it (may find an web-developer), you've got all [rpg-php-service](https://github.com/insthync/rpg-php-service) source codes and database tables it would help other developers to develop the email recovery system. And I also made facebook-login and google-play-login plugin, you can use it instead of normal login system.
