### ISSUE TITLE
how to activate clan sistem i dont use php use GS

### ISSUE THREAD

**Issue by surycr** [suriyun-production/turnbase-rpg-docs#53]
![image](https://user-images.githubusercontent.com/43394702/77968737-491c8e80-72a5-11ea-8aa0-bec7714dca23.png)

**Comment by dclgamingtr** [comment]
Recommend using php system.

**Comment by dclgamingtr** [comment]
Currently only valid in php.

**Comment by surycr** [comment]
i dont know how use php use bad

**Comment by surycr** [comment]
but I already have everything with game spark, since it is even how the page explains how to configure, I thought it would be useful for Gamespark

**Comment by dclgamingtr** [comment]
Using php is easier.  Using to  more hard gamespark.

**Comment by dclgamingtr** [comment]
If you want to install Teamwiever, I'll help you for php.

**Comment by surycr** [comment]
ok nice

**Comment by dclgamingtr** [comment]
Send your teamwiever ID and password to my email address.

**Comment by dclgamingtr** [comment]
Are you installing

**Comment by dclgamingtr** [comment]
https://www.teamviewer.com/en/

you can download it from this address.

**Comment by insthync** [comment]
Please wait, I will implement it for Gamespark later.

**Comment by insthync** [comment]
I decided to not implement it to GameSparks, because when there are new features I have to do integration to both PHP web-service and GameSparks, and while there is GameSparks integration there still have customer that asked for PlayFab integration and it seems like GameSparks not being uses by many people (not popular) if compare to PlayFab.

But I won't do PlayFab integration, I prefer Firebase over both GameSparks and PlayFab because of its price plan and its abilities to manage complex data.
