### ISSUE TITLE
Multiple login on one account!

### ISSUE THREAD

**Issue by brabaris** [suriyun-production/turnbase-rpg-docs#85]
You need to prohibit the entrance to one account from multiple devices!

**Comment by insthync** [comment]
When client login, it will regenerate login token 

So, after `Client A` logged in, 

Then `Client B` logged in, 

After that when `Client A` do something, player will be prevented to do anything and receive error message

It's about architecture, the current PHP web-service was designed to works with shared hosts, most shared hosts are supports just PHP, MySQL (or MariaDB), we won't be able to use real-time stuff such as WebSocket on most shared hosts.

You may doubt why Chat works, it working because it do short-polling to update data every `X` seconds, this way is use pretty a lot of resources so I won't do it frequently.

And as I known Unity's web request cannot do server-sent events request, and I not sure that PHP can do server-sent events without plugins or not.
